#
# code-facebook
#
PORTNAME=	code-facebook
PORTVERSION=	0
CATEGORIES=	devel

MAINTAINER=	sbz
COMMENT=	Facebook tools

BUILD_DEPENDS=	${PORTSDIR}/devel/arcanist \
		${PORTSDIR}/devel/libphutil

RUN_DEPENDS=	${BUILD_DEPENDS}

MASTERDIR=	${.CURDIR}/../

.include "${MASTERDIR}/meta.common.mk"
