#
# sec-net
#
PORTNAME=	sec-net
PORTVERSION=	0
CATEGORIES=	net security

MAINTAINER=	sbz
COMMENT=	Network security tools

BUILD_DEPENDS=	${PORTSDIR}/net/scapy \
		${PORTSDIR}/net/ngrep

RUN_DEPENDS=	${BUILD_DEPENDS}

MASTERDIR=	${.CURDIR}/../

.include "${MASTERDIR}/meta.common.mk"
