#
# sec-cracking
#
PORTNAME=	sec-cracking
PORTVERSION=	0
CATEGORIES=	security

MAINTAINER=	antoine
COMMENT=	Password cracking tools

RUN_DEPENDS=	ADMsmnp:${PORTSDIR}/security/ADMsnmp \
		aircrack-ng:${PORTSDIR}/net-mgmt/aircrack-ng \
		authforce:${PORTSDIR}/security/authforce \
		crack:${PORTSDIR}/security/crack \
		fcrackzip:${PORTSDIR}/security/fcrackzip \
		hydra:${PORTSDIR}/security/hydra \
		john:${PORTSDIR}/security/john \
		l0phtcrack:${PORTSDIR}/security/l0phtcrack \
		mdcrack:${PORTSDIR}/security/mdcrack \
		medusa:${PORTSDIR}/security/medusa \
		ncrack:${PORTSDIR}/security/ncrack \
		ophcrack:${PORTSDIR}/security/ophcrack \
		pdfcrack:${PORTSDIR}/security/pdfcrack \
		pkcrack:${PORTSDIR}/security/pkcrack \
		rainbowcrack:${PORTSDIR}/security/rainbowcrack \
		rarcrack:${PORTSDIR}/security/rarcrack \
		slurpie:${PORTSDIR}/security/slurpie \
		truecrack:${PORTSDIR}/security/truecrack \
		vnccrack:${PORTSDIR}/security/vnccrack

RUN_DEPENDS=	${BUILD_DEPENDS}

MASTERDIR=	${.CURDIR}/../

.include "${MASTERDIR}/meta.common.mk"
