#
# code-dbg
#
PORTNAME=	code-dbg
PORTVERSION=	0
CATEGORIES=	devel

MAINTAINER=	sbz
COMMENT=	Code debugging tools

BUILD_DEPENDS=	${PORTSDIR}/devel/gdb \
		${PORTSDIR}/devel/valgrind

RUN_DEPENDS=	${BUILD_DEPENDS}

MASTERDIR=	${.CURDIR}/../

.include "${MASTERDIR}/meta.common.mk"
